sunxi: fix build with gcc7
Building with gcc7 causes

	../include/linux/compiler-gcc.h:93:1: fatal error: linux/compiler-gcc7.h: No such file or directory

Signed-off-by: Trevor Woerner <twoerner@gmail.com>